# **Instituto Tecnológico Vale**

## **Introdução ao Pytorch**

Documentação do pytorch: https://pytorch.org/docs/stable/index.html

## **Exemplo prático**

In [ ]:
import torch

import numpy as np

### Criação de um escalar

In [ ]:
# Criação de escalar com numpy

x = np.array(0)

print(x)

print(type(x))

0
<class 'numpy.ndarray'>


In [ ]:
# Criação de escalar com torch

x_torch = torch.tensor(0)

print(x_torch)

print(type(x_torch))

tensor(0)
<class 'torch.Tensor'>


### Criação de um vetor

In [ ]:
# Criação de vetor com numpy

v = np.array([0, 1, 2])

print(v)

print(type(v))

[0 1 2]
<class 'numpy.ndarray'>


In [ ]:
# Criação de vetor com torch

v_torch = torch.tensor([0, 1, 2])

print(v_torch)

print(type(v_torch))

tensor([0, 1, 2])
<class 'torch.Tensor'>


### Criação de uma matriz

In [ ]:
m_torch = torch.tensor([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

print(m_torch)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### Criação de um tensor

In [ ]:
t_troch = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                        
                        [[9, 8, 7],
                         [6, 5, 4],
                         [3, 2, 1]]])

print(t_torch)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]])


### Olhando os shapes das variáveis

In [ ]:
print(f'shape do escalar: {x_torch.shape}')
print(f'shape do vetor: {v_torch.shape}')
print(f'shape da matriz: {m_torch.shape}')
print(f'shape do tensor: {t_torch.shape}')

shape do escalar: torch.Size([])
shape do vetor: torch.Size([3])
shape da matriz: torch.Size([3, 3])
shape do tensor: torch.Size([2, 3, 3])


### Criando variável aleatória

In [ ]:
t2_tensor = torch.rand((5,5))

print(t2_tensor)

tensor([[0.3694, 0.9419, 0.2494, 0.4030, 0.7788],
        [0.6892, 0.9290, 0.1896, 0.9018, 0.7606],
        [0.4270, 0.1003, 0.3933, 0.9713, 0.5000],
        [0.8639, 0.7742, 0.6098, 0.6864, 0.1930],
        [0.8558, 0.8491, 0.0849, 0.8728, 0.6311]])


In [ ]:
#t2_tensor = torch.tensor(torch.rand((3,5,5))*255, dtype=torch.uint8)

print(t2_tensor)

### Operações

In [ ]:
x = torch.tensor(5.)
y = torch.tensor(10.)

z = x+y
print(z)

tensor(15.)


### Autograd

In [ ]:
# variáveis 

a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

Vamos criar uma função: $q = 3a^3 - b^2$

In [ ]:
# vamos criar a função: 3a^3 - b^2

q = 3*a**3 - b**2

- Vamos assumir a e b como parâmetros de um problema e q a nosas função de erro. 

- Quais são os gradiantes do erro???

  $\frac{\partial q}{\partial a} = 9a^2$

  $\frac{\partial q}{\partial b} = -2b$

In [ ]:
# Calculando os gradiantes

q.backward()

In [ ]:
print(f'gradiente de a: {a.grad}')

print(f'gradiente de b: {b.grad}')

gradiente de a: tensor([36.])
gradiente de b: tensor([-12.])


### Autograd em cadeia

In [ ]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [ ]:
# primeira equação

q = 3*a**3 - b**2

In [ ]:
#segunda equação

z = 3*q

In [ ]:
# Calculando os gradiantes em função de z.

z.backward()

In [ ]:
print(f'gradiente de a: {a.grad}')

print(f'gradiente de b: {b.grad}')

gradiente de a: tensor([108.])
gradiente de b: tensor([-36.])


Lembre que z = 3q é uma função composta, logo:

$\frac{\partial z}{\partial a} = \frac{\partial z}{\partial q} \cdot \frac{\partial q}{\partial a} = 3 \cdot 9a^2$

$\frac{\partial z}{\partial b} = \frac{\partial z}{\partial q} \cdot \frac{\partial q}{\partial b} = 3 \cdot -2b$

Gradientes de um vetor

In [141]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [144]:
q = 3*a**3 - b**2

In [143]:
external_grad = torch.tensor([1., 1.])
q.backward(gradient=external_grad)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [137]:
print(f'gradiente de a: {a.grad}')

print(f'gradiente de b: {b.grad}')

gradiente de a: tensor([36., 81.])
gradiente de b: tensor([-12.,  -8.])
